-- Run this full script in Supabase SQL Editor.
-- It creates a simple admin system with session tokens and RPC functions
-- so your frontend can manage teams and fixtures after admin login.

create extension if not exists pgcrypto;

create table if not exists public.admin_login (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.admin_sessions (
    id uuid primary key default gen_random_uuid(),
    admin_id bigint not null references public.admin_login(id) on delete cascade,
    session_token text not null unique,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.teams (
    id bigint generated by default as identity primary key,
    team_name text not null unique,
    team_group text not null default 'A' check (team_group in ('A', 'B')),
    created_at timestamp with time zone not null default now()
);

create table if not exists public.fixtures (
    id bigint generated by default as identity primary key,
    match_date date not null,
    match_time time not null,
    home_team_id bigint not null references public.teams(id) on delete restrict,
    away_team_id bigint not null references public.teams(id) on delete restrict,
    home_score integer not null default 0,
    away_score integer not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint fixtures_distinct_teams check (home_team_id <> away_team_id),
    constraint fixtures_non_negative_scores check (home_score >= 0 and away_score >= 0)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_fixtures_updated_at on public.fixtures;
create trigger trg_fixtures_updated_at
before update on public.fixtures
for each row
execute function public.set_updated_at();

create or replace function public.require_admin_session(p_session_token text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_admin_id bigint;
begin
    select s.admin_id
    into v_admin_id
    from public.admin_sessions s
    where s.session_token = p_session_token
      and s.expires_at > now()
    limit 1;

    if v_admin_id is null then
        raise exception 'INVALID_OR_EXPIRED_SESSION';
    end if;

    return v_admin_id;
end;
$$;

create or replace function public.validate_admin_login(
    p_email text,
    p_password text
)
returns table (
    ok boolean,
    admin_id bigint,
    session_token text
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_admin public.admin_login%rowtype;
    v_session_token text;
begin
    select *
    into v_admin
    from public.admin_login
    where lower(email) = lower(trim(p_email))
    limit 1;

    if not found then
        return query select false, null::bigint, null::text;
        return;
    end if;

    if v_admin.password_hash <> crypt(p_password, v_admin.password_hash) then
        return query select false, null::bigint, null::text;
        return;
    end if;

    v_session_token := encode(gen_random_bytes(24), 'hex');

    insert into public.admin_sessions (admin_id, session_token, expires_at)
    values (v_admin.id, v_session_token, now() + interval '12 hours');

    return query select true, v_admin.id, v_session_token;
end;
$$;

create or replace function public.admin_logout(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.admin_sessions where session_token = p_session_token;
    return true;
end;
$$;

create or replace function public.admin_list_teams(p_session_token text)
returns table (
    id bigint,
    team_name text,
    team_group text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    return query
    select t.id, t.team_name, t.team_group
    from public.teams t
    order by t.team_group, t.team_name;
end;
$$;

create or replace function public.admin_add_team(
    p_session_token text,
    p_team_name text,
    p_team_group text
)
returns table (
    ok boolean,
    message text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    insert into public.teams (team_name, team_group)
    values (trim(p_team_name), upper(trim(p_team_group)));

    return query select true, 'TEAM_ADDED';
exception
    when unique_violation then
        return query select false, 'TEAM_ALREADY_EXISTS';
    when check_violation then
        return query select false, 'INVALID_GROUP_USE_A_OR_B';
end;
$$;

create or replace function public.admin_update_team_group(
    p_session_token text,
    p_team_id bigint,
    p_team_group text
)
returns table (
    ok boolean,
    message text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    update public.teams
    set team_group = upper(trim(p_team_group))
    where id = p_team_id;

    if not found then
        return query select false, 'TEAM_NOT_FOUND';
        return;
    end if;

    return query select true, 'TEAM_GROUP_UPDATED';
exception
    when check_violation then
        return query select false, 'INVALID_GROUP_USE_A_OR_B';
end;
$$;

create or replace function public.admin_list_fixtures(p_session_token text)
returns table (
    id bigint,
    match_date date,
    match_time time,
    home_team_id bigint,
    away_team_id bigint,
    home_team text,
    away_team text,
    home_score integer,
    away_score integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    return query
    select
        f.id,
        f.match_date,
        f.match_time,
        f.home_team_id,
        f.away_team_id,
        ht.team_name as home_team,
        at.team_name as away_team,
        f.home_score,
        f.away_score
    from public.fixtures f
    join public.teams ht on ht.id = f.home_team_id
    join public.teams at on at.id = f.away_team_id
    order by f.match_date, f.match_time;
end;
$$;

create or replace function public.admin_add_fixture(
    p_session_token text,
    p_match_date date,
    p_match_time time,
    p_home_team_id bigint,
    p_away_team_id bigint
)
returns table (
    ok boolean,
    message text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    insert into public.fixtures (
        match_date,
        match_time,
        home_team_id,
        away_team_id
    )
    values (
        p_match_date,
        p_match_time,
        p_home_team_id,
        p_away_team_id
    );

    return query select true, 'FIXTURE_ADDED';
exception
    when check_violation then
        return query select false, 'INVALID_FIXTURE_VALUES';
    when foreign_key_violation then
        return query select false, 'TEAM_NOT_FOUND';
end;
$$;

create or replace function public.admin_update_fixture(
    p_session_token text,
    p_fixture_id bigint,
    p_match_date date,
    p_match_time time,
    p_home_team_id bigint,
    p_away_team_id bigint,
    p_home_score integer,
    p_away_score integer
)
returns table (
    ok boolean,
    message text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.require_admin_session(p_session_token);

    update public.fixtures
    set match_date = p_match_date,
        match_time = p_match_time,
        home_team_id = p_home_team_id,
        away_team_id = p_away_team_id,
        home_score = p_home_score,
        away_score = p_away_score
    where id = p_fixture_id;

    if not found then
        return query select false, 'FIXTURE_NOT_FOUND';
        return;
    end if;

    return query select true, 'FIXTURE_UPDATED';
exception
    when check_violation then
        return query select false, 'INVALID_FIXTURE_VALUES';
    when foreign_key_violation then
        return query select false, 'TEAM_NOT_FOUND';
end;
$$;

revoke all on table public.admin_login from anon, authenticated, public;
revoke all on table public.admin_sessions from anon, authenticated, public;
revoke all on table public.teams from anon, authenticated, public;
revoke all on table public.fixtures from anon, authenticated, public;

revoke all on function public.require_admin_session(text) from public;
revoke all on function public.validate_admin_login(text, text) from public;
revoke all on function public.admin_logout(text) from public;
revoke all on function public.admin_list_teams(text) from public;
revoke all on function public.admin_add_team(text, text, text) from public;
revoke all on function public.admin_update_team_group(text, bigint, text) from public;
revoke all on function public.admin_list_fixtures(text) from public;
revoke all on function public.admin_add_fixture(text, date, time, bigint, bigint) from public;
revoke all on function public.admin_update_fixture(text, bigint, date, time, bigint, bigint, integer, integer) from public;

grant execute on function public.validate_admin_login(text, text) to anon, authenticated;
grant execute on function public.admin_logout(text) to anon, authenticated;
grant execute on function public.admin_list_teams(text) to anon, authenticated;
grant execute on function public.admin_add_team(text, text, text) to anon, authenticated;
grant execute on function public.admin_update_team_group(text, bigint, text) to anon, authenticated;
grant execute on function public.admin_list_fixtures(text) to anon, authenticated;
grant execute on function public.admin_add_fixture(text, date, time, bigint, bigint) to anon, authenticated;
grant execute on function public.admin_update_fixture(text, bigint, date, time, bigint, bigint, integer, integer) to anon, authenticated;

-- Create your first admin user (change these values)
insert into public.admin_login (email, password_hash)
values ('admin@example.com', crypt('admin123', gen_salt('bf')))
on conflict (email) do nothing;
